# Flux Instance Chart Values
# This chart creates GitRepository for GitOps
# Kustomizations are static files in manifests/kustomizations/
# HelmReleases are static files in manifests/releases/<category>/

gitRepository:
  name: flux-system
  url: git@github.com:Lab-Brat/k8s-dev.git
  branch: main
  interval: 1m

gitCredentials:
  enabled: false
  type: https
  username: ""
  password: ""
  # SSH fields
  identity: ""
  identityPub: ""
  knownHosts: ""

