apiVersion: v2
name: prometheus-operator-crds
version: 26.0.0
description: Wrapper for Prometheus Operator CRDs
dependencies:
- name: prometheus-operator-crds
  version: 26.0.0
  repository: file://charts/prometheus-operator-crds

